version: "3.8"
services:
  frontend:
    container_name: stocktree-frontend
    image: insd47/stocktree-frontend:latest
    restart: unless-stopped
    networks:
      stocktree_bridge:
          ipv4_address: 172.30.1.2
  backend:
    container_name: stocktree-backend
    image: insd47/stocktree-backend:latest
    restart: unless-stopped
    environment:
      CLOUD_AWS_CREDENTIALS_ACCESSKEY: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      CLOUD_AWS_CREDENTIALS_SECRETKEY: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      stocktree_bridge:
          ipv4_address: 172.30.1.3
  backend_dev:
    container_name: stocktree-backend-dev
    image: insd47/stocktree-backend:development
    restart: unless-stopped
    environment:
      CLOUD_AWS_CREDENTIALS_ACCESSKEY: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      CLOUD_AWS_CREDENTIALS_SECRETKEY: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      stocktree_bridge:
          ipv4_address: 172.30.1.4
  caddy:
    container_name: stocktree-caddy
    build:
      context: ./caddy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8443:8443"
    networks:
      stocktree_bridge:
          ipv4_address: 172.30.1.5
    cap_add:
      - NET_ADMIN
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      ACME_AGREE: true
      ACME_CA: https://acme-v02.api.letsencrypt.org/directory
      ACME_EMAIL: me@insd.dev
      CLOUDFLARE_AUTH_TOKEN: ${CLOUDFLARE_AUTH_TOKEN}

networks:
  stocktree_bridge:
    name: stocktree-bridge
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
          gateway: 172.30.1.1